# -*- coding: utf-8 -*-
"""quantum_shor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jykoUI4H3owOOO2drhT1mwUIwhINwqah
"""

!pip install qiskit

from qiskit.algorithms import Shor
from qiskit.utils import QuantumInstance 
from qiskit import Aer

key = 69
base = 2


backend = Aer.get_backend('qasm_simulator')

qi = QuantumInstance(backend=backend , shots = 1024)

shors = Shor(qi)

results = shors.factor(N=15,a=2)

print(results)

